version: '3'

services:

  mailing:
    build:
      args:
        - NAME=mailing
    volumes:
      - ./database/kgtt.sqlite:/app/database/kgtt.sqlite
      - ./logs:/app/logs/
    command: python start.py

    restart: always
  bot:
    build:
      args:
        - NAME=bot
    volumes:
      - ./database/kgtt.sqlite:/app/database/kgtt.sqlite
      - ./logs:/app/logs/
    command: python start.py
    depends_on:
      - mailing
    restart: always
